spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secretKey: F52D3FF3586173985E6ECDCED1DF9dsfasdfjhashflhsdlkjfdhalsdkhflaskhfjdhafluhfsdkjfhalseufhlkasjdhflauehkabvjklsdbuhlashfei
  access:
    expiration: 86400
    header: Authorization
  refresh:
    expiration: 864000
    header: Authorization-refresh